nacosconfig:
  nserverconfig:
    host: "192.168.10.12"
    port: "8848"
  nclientconfig:
    namespace: "24ce0a70-b0e3-4e59-a8e1-dfc6ec0431b8"
    timeoutms: 500
    logdir: "/tmp/nacos/log"
    cachedir: "/tmp/nacos/cache"
    loglevel: "debug"




