nacosconfig:
  nserverconfig:
    host: "192.168.10.12"
    port: "8848"
  nclientconfig:
    namespace: "d058ebe2-1727-49bf-a053-4507b0b40215"
    timeoutms: 500
    logdir: "/tmp/nacos/log"
    cachedir: "/tmp/nacos/cache"
    loglevel: "debug"




