nacosconfig:
  nserverconfig:
    host: "192.168.10.12"
    port: "8848"
  nclientconfig:
    namespace: "f9665ca2-ef0e-44f1-9227-61c27085f9e2"
    timeoutms: 500
    logdir: "/tmp/nacos/log"
    cachedir: "/tmp/nacos/cache"
    loglevel: "debug"




