nacosconfig:
  nserverconfig:
    host: "192.168.10.12"
    port: "8848"
  nclientconfig:
    namespace: "f9665ca2-ef0e-44f1-9227-61c27085f9e2"
    timeoutms: 500
    logdir: "/tmp/nacos/log"
    cachedir: "/tmp/nacos/cache"
    loglevel: "debug"

# =========下面弃用当作demo，已经进入nacos配置============
#Jwt:
#  signingkey: 'IKbr3XUWZV9CUYlq'
#
#
#userWeb:
#  host: "127.0.0.1"
#  port: 8899
#
#usersrv:
#  host: "127.0.0.1"
#  port: 50053
#  name: "usr-srv"
#
#redisconfig:
#  host: "127.0.0.1"
#  port: 6379
#  expire: 360
#
#consulconfig:
#  host: "127.0.0.1"
#  port: 8500
#



